enum AppRoute {
  login,
  tenantSelection,
  portal,
  adminMenu,
  adminMenuCategories,
  adminMenuAddCategory,
  adminMenuEditCategory,
  adminMenuModifiers,
  adminMenuAddModifierGroup,
  adminMenuViewModifierGroup,
  adminMenuEditModifierGroup,
  adminMenuItemForm,
  adminMenuViewMenuItem,
  components,
  policy,
  policyVatDetail,
  policyItemDetail,
  account,
  settings,
  attendance,
  inventory,
  inventoryAddItem,
  inventoryStockDetail,
  inventoryAdjustStock,
  inventoryStockItems,
  inventoryRestock,
  inventoryCategories,
  inventoryAddCategory,
  inventoryJournal,
  inventoryJournalDetail,
  staff,
  staffDetail,
  staffForm,
  staffAdd,
  orders,
  orderDetail,
  sale,
  saleCart,
  saleItemDetail,
  saleViewCarts,
  saleViewCartDetail,
  cashSession,
  xReport,
  zReport,
  attendanceManagement,
}

extension AppRoutePath on AppRoute {
  String get path => switch (this) {
    AppRoute.login => '/login',
    AppRoute.tenantSelection => '/select-tenant',
    AppRoute.portal => '/portal',
    AppRoute.adminMenu => '/menu',
    AppRoute.adminMenuCategories => '/menu/categories',
    AppRoute.adminMenuAddCategory => '/menu/categories/add',
    AppRoute.adminMenuEditCategory => '/menu/categories/edit',
    AppRoute.adminMenuModifiers => '/menu/modifiers',
    AppRoute.adminMenuAddModifierGroup => '/menu/modifiers/add',
    AppRoute.adminMenuViewModifierGroup => '/menu/modifiers/view',
    AppRoute.adminMenuEditModifierGroup => '/menu/modifiers/edit',
    AppRoute.adminMenuItemForm => '/menu/items/form',
    AppRoute.adminMenuViewMenuItem => '/menu/items/view',
    AppRoute.components => '/components',
    AppRoute.policy => '/policy',
    AppRoute.policyVatDetail => '/policy/vat',
    AppRoute.policyItemDetail => '/policy/item',
    AppRoute.account => '/account',
    AppRoute.settings => '/settings',
    AppRoute.attendance => '/attendance',
    AppRoute.inventory => '/inventory',
    AppRoute.inventoryAddItem => '/inventory/add-item',
    AppRoute.inventoryStockDetail => '/inventory/detail',
    AppRoute.inventoryAdjustStock => '/inventory/adjust',
    AppRoute.inventoryStockItems => '/inventory/stock-items',
    AppRoute.inventoryRestock => '/inventory/restock',
    AppRoute.inventoryCategories => '/inventory/categories',
    AppRoute.inventoryAddCategory => '/inventory/categories/add',
    AppRoute.inventoryJournal => '/inventory/journal',
    AppRoute.inventoryJournalDetail => '/inventory/journal/detail',
    AppRoute.staff => '/staff',
    AppRoute.staffDetail => '/staff/detail',
    AppRoute.staffForm => '/staff/form',
    AppRoute.staffAdd => '/staff/add',
    AppRoute.orders => '/sale/orders',
    AppRoute.orderDetail => '/sale/orders/detail',
    AppRoute.sale => '/sale',
    AppRoute.saleCart => '/sale/cart',
    AppRoute.saleItemDetail => '/sale/item',
    AppRoute.saleViewCarts => '/sale/carts',
    AppRoute.saleViewCartDetail => '/sale/carts/detail',
    AppRoute.cashSession => '/cash/session',
    AppRoute.xReport => '/reports/x',
    AppRoute.zReport => '/reports/z',
    AppRoute.attendanceManagement => '/attendance/manage',
  };

  String get name => switch (this) {
    AppRoute.login => 'login',
    AppRoute.tenantSelection => 'tenantSelection',
    AppRoute.portal => 'portal',
    AppRoute.adminMenu => 'adminMenu',
    AppRoute.adminMenuCategories => 'adminMenuCategories',
    AppRoute.adminMenuAddCategory => 'adminMenuAddCategory',
    AppRoute.adminMenuEditCategory => 'adminMenuEditCategory',
    AppRoute.adminMenuModifiers => 'adminMenuModifiers',
    AppRoute.adminMenuAddModifierGroup => 'adminMenuAddModifierGroup',
    AppRoute.adminMenuViewModifierGroup => 'adminMenuViewModifierGroup',
    AppRoute.adminMenuEditModifierGroup => 'adminMenuEditModifierGroup',
    AppRoute.adminMenuItemForm => 'adminMenuItemForm',
    AppRoute.adminMenuViewMenuItem => 'adminMenuViewMenuItem',
    AppRoute.components => 'components',
    AppRoute.policy => 'policy',
    AppRoute.policyVatDetail => 'policyVatDetail',
    AppRoute.policyItemDetail => 'policyItemDetail',
    AppRoute.account => 'account',
    AppRoute.settings => 'settings',
    AppRoute.attendance => 'attendance',
    AppRoute.inventory => 'inventory',
    AppRoute.inventoryAddItem => 'inventoryAddItem',
    AppRoute.inventoryStockDetail => 'inventoryStockDetail',
    AppRoute.inventoryAdjustStock => 'inventoryAdjustStock',
    AppRoute.inventoryStockItems => 'inventoryStockItems',
    AppRoute.inventoryRestock => 'inventoryRestock',
    AppRoute.inventoryCategories => 'inventoryCategories',
    AppRoute.inventoryAddCategory => 'inventoryAddCategory',
    AppRoute.inventoryJournal => 'inventoryJournal',
    AppRoute.inventoryJournalDetail => 'inventoryJournalDetail',
    AppRoute.staff => 'staff',
    AppRoute.staffDetail => 'staffDetail',
    AppRoute.staffForm => 'staffForm',
    AppRoute.staffAdd => 'staffAdd',
    AppRoute.orders => 'orders',
    AppRoute.orderDetail => 'orderDetail',
    AppRoute.sale => 'sale',
    AppRoute.saleCart => 'saleCart',
    AppRoute.saleItemDetail => 'saleItemDetail',
    AppRoute.saleViewCarts => 'saleViewCarts',
    AppRoute.saleViewCartDetail => 'saleViewCartDetail',
    AppRoute.cashSession => 'cashSession',
    AppRoute.xReport => 'xReport',
    AppRoute.zReport => 'zReport',
    AppRoute.attendanceManagement => 'attendanceManagement',
  };
}
