enum AppRoute {
  login,
  tenantSelection,
  adminPortal,
  adminMenu,
  adminMenuCategories,
  adminMenuAddCategory,
  adminMenuEditCategory,
  adminMenuModifiers,
  adminMenuAddModifierGroup,
  adminMenuViewModifierGroup,
  adminMenuEditModifierGroup,
  adminMenuItemForm,
  adminMenuViewMenuItem,
  cashierPortal,
  components,
  policy,
  policyVatDetail,
  policyItemDetail,
  account,
  settings,
  attendance,
  inventory,
  inventoryAddItem,
  inventoryStockDetail,
  inventoryAdjustStock,
  inventoryStockItems,
  inventoryRestock,
  inventoryCategories,
  inventoryJournal,
  inventoryJournalDetail,
  staff,
  staffDetail,
  staffForm,
  staffAdd,
  orders,
  orderDetail,
  sale,
  saleCart,
  saleItemDetail,
  saleViewCarts,
  saleViewCartDetail,
  adminCashSession,
  cashierCashSession,
  xReport,
  zReport,
  attendanceManagement,
}

extension AppRoutePath on AppRoute {
  String get path => switch (this) {
    AppRoute.login => '/login',
    AppRoute.tenantSelection => '/select-tenant',
    AppRoute.adminPortal => '/portal/admin',
    AppRoute.adminMenu => '/portal/admin/menu',
    AppRoute.adminMenuCategories => '/portal/admin/menu/categories',
    AppRoute.adminMenuAddCategory => '/portal/admin/menu/categories/add',
    AppRoute.adminMenuEditCategory => '/portal/admin/menu/categories/edit',
    AppRoute.adminMenuModifiers => '/portal/admin/menu/modifiers',
    AppRoute.adminMenuAddModifierGroup => '/portal/admin/menu/modifiers/add',
    AppRoute.adminMenuViewModifierGroup => '/portal/admin/menu/modifiers/view',
    AppRoute.adminMenuEditModifierGroup => '/portal/admin/menu/modifiers/edit',
    AppRoute.adminMenuItemForm => '/portal/admin/menu/items/form',
    AppRoute.adminMenuViewMenuItem => '/portal/admin/menu/items/view',
    AppRoute.cashierPortal => '/portal/cashier',
    AppRoute.components => '/components',
    AppRoute.policy => '/portal/admin/policy',
    AppRoute.policyVatDetail => '/portal/admin/policy/vat',
    AppRoute.policyItemDetail => '/portal/admin/policy/item',
    AppRoute.account => '/account',
    AppRoute.settings => '/settings',
    AppRoute.attendance => '/portal/cashier/attendance',
    AppRoute.inventory => '/portal/admin/inventory',
    AppRoute.inventoryAddItem => '/portal/admin/inventory/add-item',
    AppRoute.inventoryStockDetail => '/portal/admin/inventory/detail',
    AppRoute.inventoryAdjustStock => '/portal/admin/inventory/adjust',
    AppRoute.inventoryStockItems => '/portal/admin/inventory/stock-items',
    AppRoute.inventoryRestock => '/portal/admin/inventory/restock',
    AppRoute.inventoryCategories => '/portal/admin/inventory/categories',
    AppRoute.inventoryJournal => '/portal/admin/inventory/journal',
    AppRoute.inventoryJournalDetail => '/portal/admin/inventory/journal/detail',
    AppRoute.staff => '/portal/admin/staff',
    AppRoute.staffDetail => '/portal/admin/staff/detail',
    AppRoute.staffForm => '/portal/admin/staff/form',
    AppRoute.staffAdd => '/portal/admin/staff/add',
    AppRoute.orders => '/orders',
    AppRoute.orderDetail => '/orders/detail',
    AppRoute.sale => '/sale',
    AppRoute.saleCart => '/sale/cart',
    AppRoute.saleItemDetail => '/sale/item',
    AppRoute.saleViewCarts => '/sale/carts',
    AppRoute.saleViewCartDetail => '/sale/carts/detail',
    AppRoute.adminCashSession => '/portal/admin/session',
    AppRoute.cashierCashSession => '/portal/cashier/session',
    AppRoute.xReport => '/portal/x-report',
    AppRoute.zReport => '/portal/admin/z-report',
    AppRoute.attendanceManagement => '/portal/admin/attendance-management',
  };

  String get name => switch (this) {
    AppRoute.login => 'login',
    AppRoute.tenantSelection => 'tenantSelection',
    AppRoute.adminPortal => 'adminPortal',
    AppRoute.adminMenu => 'adminMenu',
    AppRoute.adminMenuCategories => 'adminMenuCategories',
    AppRoute.adminMenuAddCategory => 'adminMenuAddCategory',
    AppRoute.adminMenuEditCategory => 'adminMenuEditCategory',
    AppRoute.adminMenuModifiers => 'adminMenuModifiers',
    AppRoute.adminMenuAddModifierGroup => 'adminMenuAddModifierGroup',
    AppRoute.adminMenuViewModifierGroup => 'adminMenuViewModifierGroup',
    AppRoute.adminMenuEditModifierGroup => 'adminMenuEditModifierGroup',
    AppRoute.adminMenuItemForm => 'adminMenuItemForm',
    AppRoute.adminMenuViewMenuItem => 'adminMenuViewMenuItem',
    AppRoute.cashierPortal => 'cashierPortal',
    AppRoute.components => 'components',
    AppRoute.policy => 'policy',
    AppRoute.policyVatDetail => 'policyVatDetail',
    AppRoute.policyItemDetail => 'policyItemDetail',
    AppRoute.account => 'account',
    AppRoute.settings => 'settings',
    AppRoute.attendance => 'attendance',
    AppRoute.inventory => 'inventory',
    AppRoute.inventoryAddItem => 'inventoryAddItem',
    AppRoute.inventoryStockDetail => 'inventoryStockDetail',
    AppRoute.inventoryAdjustStock => 'inventoryAdjustStock',
    AppRoute.inventoryStockItems => 'inventoryStockItems',
    AppRoute.inventoryRestock => 'inventoryRestock',
    AppRoute.inventoryCategories => 'inventoryCategories',
    AppRoute.inventoryJournal => 'inventoryJournal',
    AppRoute.inventoryJournalDetail => 'inventoryJournalDetail',
    AppRoute.staff => 'staff',
    AppRoute.staffDetail => 'staffDetail',
    AppRoute.staffForm => 'staffForm',
    AppRoute.staffAdd => 'staffAdd',
    AppRoute.orders => 'orders',
    AppRoute.orderDetail => 'orderDetail',
    AppRoute.sale => 'sale',
    AppRoute.saleCart => 'saleCart',
    AppRoute.saleItemDetail => 'saleItemDetail',
    AppRoute.saleViewCarts => 'saleViewCarts',
    AppRoute.saleViewCartDetail => 'saleViewCartDetail',
    AppRoute.adminCashSession => 'adminCashSession',
    AppRoute.cashierCashSession => 'cashierCashSession',
    AppRoute.xReport => 'xReport',
    AppRoute.zReport => 'zReport',
    AppRoute.attendanceManagement => 'attendanceManagement',
  };
}
